### ISSUE TITLE
Protocols hanging without throwing any errors

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron#1134] opened 2020-11-02 11:20 UTC
A week ago, I brought this up at the pyiron meeting, that the new updates to get_neighbors caused the protocols I was using to hang. As suggested by @pmrv, I ran git bisect to isolate the first bad commit to the following one: 

[1cecbfb0281b3fd4947ced2d3404d54ecad86147](https://github.com/pyiron/pyiron/commit/1cecbfb0281b3fd4947ced2d3404d54ecad86147)

```
1cecbfb0281b3fd4947ced2d3404d54ecad86147 is the first bad commit
commit 1cecbfb0281b3fd4947ced2d3404d54ecad86147
Author: Sam Waseda <o.waseda@mpie.de>
Date:   Tue Sep 29 16:17:23 2020 +0200

    small bugfixes

 pyiron/atomistics/structure/neighbors.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```
I spent quite a bit of time trying to replicate this behavior outside of protocols, but was unable to.

@samwaseda I am unsure how to proceed at the moment. I await your advice. :)

**Comment by samwaseda** [comment] 2020-11-02 12:04
It's rather unlikely that this one is directly related. I have actually another question: How does the communication between LAMMPS and pyiron work? In my old C++ implementation I had to spend quite some time to understand how the local variables are transferred and how to convert them back to global variables for multiple core jobs. Can you check whether you always use interface methods which always give you global variables or you use both methods and therefore have global and MPI local variables?

**Comment by raynol-dsouza** [comment] 2020-11-02 12:43
The problem is not just persistent with parallel protocols, but also with serial protocols, which run on a single core. This makes me believe that the issue is not with the parallelization.

**Comment by liamhuber** [comment] 2020-11-02 12:45
@raynol-dsouza I also find it hard to believe that the changes in this commit are at fault; they seem entirely unrelated. Could you try checking out this commit, and then manually reverting the two lines in it? If your assertion that this commit broke things is correct, it should run again; if my suspicions are correct then it will still hang.

Unfortunately, if it *isn't* this commit that broke things, we will still need to track down what *did*....

**Comment by liamhuber** [comment] 2020-11-02 12:47
Is it possible that your bisection search has an off-by-one error? Like the actual guilty commit is one commit before (or after) this one?

**Comment by raynol-dsouza** [comment] 2020-11-02 12:58
@samwaseda @liamhuber I was wrong. I just confirmed that the serial protocols are working as they should. So the issue must lie with parallelization.

**Comment by raynol-dsouza** [comment] 2020-11-02 13:18
So the line which causes the hang is this one: 

`from sklearn.cluster import MeanShift`

weird, right? Why would an import cause a hang like this?

**Comment by pmrv** [comment] 2020-11-02 13:50
How are you checking where it hangs?  If you run from a notebook or terminal, try to interrupt the process (Interrupt Kernel or ctrl-c) and then use the `%debug` magic in the next cell/line.  It should put you in a debug shell where your process was interrupted.  You can then inspect the backtrace with `bt` and climb up and down the stack with `up`/`down`.  This might give you a better idea where your process is really hanging.

**Comment by raynol-dsouza** [comment] 2020-11-02 14:16
I could not interrupt the process. So I ran `%debug ` before running the protocol job itself, so it would print the debug message white running the process itself. 

```
DEBUG:pyiron_log:Not supported parameter used!

The job tild_job_initialize_vac_jobs_2 was saved and received the ID: 286

DEBUG:pyiron_log:Not supported parameter used!

The job tild_job_initialize_vac_jobs_3 was saved and received the ID: 287

DEBUG:pyiron_log:Not supported parameter used!

The job tild_job_initialize_vac_jobs_4 was saved and received the ID: 288
```

`pyiron_log:Not supported parameter used!` seems to be a message that is printed every time a pyiron job is created. And this is all that I see in the debug.

**Comment by jan-janssen** [comment] 2020-11-02 14:22
You can try to set the drug level using: 
```
pr.set_logging_level("DEBUG")
```

**Comment by raynol-dsouza** [comment] 2020-11-02 14:25
> You can try to set the debug level using:

Doing it this way still gives the same result as above.

**Comment by jan-janssen** [comment] 2020-11-02 14:28
But then there is something wrong because when running the debug command in combination with Lammps interactive you should see the commands pyiron is communicating to Lammps.

**Comment by raynol-dsouza** [comment] 2020-11-02 14:33
Yes, true. But the hang happens before pyiron has a chance to communicate with Lammps. As I mentioned last week, it happens while running ASE's `find_mic`, which in the protocols, comes before Lammps interactive is called.

**Comment by jan-janssen** [comment] 2020-11-02 14:35
Ok, but then there is something else wrong. Can you compile as small example which breaks at the current master and works with the old code.

**Comment by raynol-dsouza** [comment] 2020-11-02 14:41
I tried this already, but couldn't replicate the behavior with a smaller (non-parallel) example. I know it is very difficult to understand where the problem lies when there is no small snippet which can show where the break is happening. I will try it again and update here when I have managed to do it.

**Comment by raynol-dsouza** [comment] 2020-11-03 14:37
So upgrading the ipykernel (as mentioned in [this stack question](https://stackoverflow.com/questions/46383177/jupyter-notebook-not-running-code-stuck-on-in)) fixed the problem on my local system. 

@jan-janssen, do you know if the cluster ipykernel is running on the latest version?

**Comment by jan-janssen** [comment] 2020-11-03 14:57
```
ipykernel                 5.3.4            py37hc6149b9_1    conda-forge
```

**Comment by raynol-dsouza** [comment] 2020-11-03 15:14
That's the same version that I am on currently, after the update. I will check once again on the cluster.

**Comment by raynol-dsouza** [comment] 2020-11-03 16:21
It also works on the cluster. :) thanks for the assist!

**Comment by jan-janssen** [comment] 2020-11-03 16:22
Mmh, Can you explain where the error is coming from? Why does it depend on the version of the ipykernel ?

**Comment by raynol-dsouza** [comment] 2020-11-03 16:34
To be honest, I do not know the reason. The [stack](https://stackoverflow.com/questions/46383177/jupyter-notebook-not-running-code-stuck-on-in) lists a number of things that could've gone wrong, and my local system satisfies more than 1 of them (ad-blocker on the Firefox browser that I use to run jupyter, Windows defender etc.). It is wholly possible that my ipykernel was in some way corrupted, and an upgrade or a clean installation would have solved the problem. 

But that does not answer the question of why it would hang at the current master, but work with the old code.

**Comment by jan-janssen** [comment] 2020-11-03 16:40
Ok, I am fine with closing this issue, still it is a bit frustrating that we are not able to identify the root cause of the issue.

**Comment by raynol-dsouza** [comment] 2020-11-03 16:42
Haha, I understand this well. I spent nearly a month on figuring out where this problem was coming from. Updating/re-installing ipykernel didn't even occur to me as a possible cause. xD

**Closed** 2020-11-03 18:15 UTC
Labels: help wanted
