### ISSUE TITLE
[URGENT] inputlist fails when job is submitted

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#748] opened 2020-06-19 20:54 UTC
These lines

```
        if group_name:
            with hdf.open(group_name) as hdf_group:
                data = hdf_group["data"]
```

in [inputlist.py](https://github.com/pyiron/pyiron/blob/master/pyiron/base/generic/inputlist.py#L536) fail when the job is submitted to the queueing system

**Comment by jan-janssen** [comment] 2020-06-19 20:56
Do we test a non modal sphinx calculation in https://github.com/pyiron/pyiron/blob/master/notebooks/tests_sphinx_sphinx_check_all.ipynb ? Maybe that is something we can add to prevent this in future.

**Comment by pmrv** [comment] 2020-06-20 17:10
Setting `job.server.run_mode = 'non_modal'` in the sphinx notebook does not reproduce the issue.  There are some pyiron warnings but the job finishes successfully and gives normal results.  Am looking into it on the cluster right now.

Sorry I didn't catch this yesterday immediately.

**Comment by jan-janssen** [comment] 2020-06-20 17:57
@pmrv it is not your mistake. We have to develop processes to prevent such issues and @samwaseda approved the pull request just like I did.

**Comment by pmrv** [comment] 2020-06-20 18:03
I ran the notebook on the cluster with `job.server.queue = 'cm'` added to all the jobs and I can't seem to trigger an error, just warnings about default parameters. 

@samwaseda Is your error related to the new tests in #750?

**Comment by jan-janssen** [comment] 2020-06-20 18:06
@samwaseda Do you still have the original error message? I updated the source reference https://github.com/pyiron/pyiron/blob/inputlist/pyiron/base/generic/inputlist.py#L536 
It seems that the issue is that `self.table_name` is `None` but this should also affect `non_modal` jobs ...

**Comment by pmrv** [comment] 2020-06-20 18:16
I added a commit to the new PR that sets the group_name to the table_name that is set in the `SphinxBase.__init__`.  I'm not sure what the code path on loading jobs from hdf5 is.  In case the job __init__ is skipped, that could lead to there being no table_name set.  This should be fixed with that commit.

**Closed** 2020-07-10 12:44 UTC
Labels: bug
