### ISSUE TITLE
Kim potentials

### ISSUE THREAD

**Issue by caglayanoaras** [pyiron/pyiron#1311] opened 2021-02-23 13:31 UTC
When I use the calcium potential 'Morse_Shifted_GirifalcoWeizer_1959HighCutoff_Ca__MO_159753408472_003', I get the error 

> ERROR: KIM ModelCreate failed (src/KIM/pair_kim.cpp:848)
Last command: pair_style kim Morse_Shifted_GirifalcoWeizer_1959HighCutoff_Ca__MO_159753408472_003

This was not the case last week and I do not get this error for other kim potentials (such az Zr). I have realized that in Kim webpage the name of the potential become 'Morse_Shifted_GirifalcoWeizer_1959HighCutoff_Ca__MO_159753408472_004' I am not sure but this might be the reason for my error.

When I try the change the name of the potential in my script I get the error 'This potential does not exist in database'. 

I am running everything in MPIE cloud.

I will be happy If I can get some assist.

**Comment by jan-janssen** [comment] 2021-02-23 15:10
@caglayanoaras Yes, the name change is the reason why it fails I created a workaround https://github.com/jan-janssen/pyiron_test_potentials/blob/master/test_openkim_Ca.ipynb

**Comment by caglayanoaras** [comment] 2021-02-23 16:19
Thank you Jan.

**Comment by jan-janssen** [comment] 2021-02-23 18:49
Seems like there is yet another issue https://github.com/lmhale99/potentials-library/issues/1

**Comment by jan-janssen** [comment] 2021-02-24 13:28
@caglayanoaras The issue is fixed in `2021.2.23`. @muh-hassani Can you update the `iprpy-data` package on cmti?

**Comment by muh-hassani** [comment] 2021-02-24 13:34
> 
> 
> @caglayanoaras The issue is fixed in `2021.2.23`. @muh-hassani Can you update the `iprpy-data` package on cmti?

@jan-janssen, done!

**Closed** 2021-02-24 14:56 UTC
Labels: bug
