### ISSUE TITLE
Troubling importing pyiron functions

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#1370] opened 2021-09-06 15:04 UTC
**Summary**

<Troubling importing pyiron functions>

**pyiron Version and Platform**

<
[DEFAULT]
TYPE = Postgres
HOST = pyiron-db-cmmc.esc.rzg.mpg.de
NAME = pyiron
USER = skanchar
PASSWD = 
JOB_TABLE = jobs_cmmc
TOP_LEVEL_DIRS = /cmmc/u
VIEWERUSER = cmmc_view
VIEWERPASSWD = 
VIEWER_TABLE = jobs_cmmc_admin
#RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc
RESOURCE_PATHS = /cmmc/u/skanchar/pyiron/pyiron-resources-cmmc, /cmmc/u/skanchar/pyiron/pyiron-resources-cmmc-p
otentiostat
#RESOURCE_PATHS = /u/skanchar/pyiron/pyiron-resources-cmmc-potentiostat
>

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**
```
import pyiron
```
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_10448/1054568024.py in <module>
----> 1 import pyiron

~/software/pyiron/pyiron/__init__.py in <module>
      2 __all__ = []
      3 
----> 4 from pyiron_atomistics.project import Project
      5 from pyiron_atomistics.atomistics.structure.atoms import ase_to_pyiron, pyiron_to_ase, Atoms
      6 from pyiron_base import Notebook, install_dialog, JOB_CLASS_DICT

ModuleNotFoundError: No module named 'pyiron_atomistics'
```
**Further Information, Files, and Links**

**Comment by jan-janssen** [comment] 2021-09-06 15:10
Can you try again? It should be fixed now.

**Comment by muh-hassani** [comment] 2021-09-06 15:13
Unfortunately some of pyiron packages were removed mistakenly. The packages are now reinstalled, I hope the issue is now solved. @sravankumarkb

**Comment by muh-hassani** [comment] 2021-09-06 15:27
I tried `import pyiron`, and it seems to be fixed now on the cluster.

**Closed by muh-hassani** 2021-09-06 15:27 UTC
Labels: bug

**Comment by sravankumarkb** [comment] 2021-09-06 16:02
It is fixed now. Thank you @muh-hassani and @jan-janssen
